### ISSUE TITLE
已按照说明配置好，昨日能用，今天突然无法使用，详细报错内容如下

### ISSUE THREAD

**Issue by AeonWorks** [zhuozhiyongde/Alfred_HeWeather_Workflow#2]
[11:12:06.334] Logging Started...
[11:12:08.602] HeWeather by Arthals[Script Filter] Queuing argument ''
[11:12:09.305] HeWeather by Arthals[Script Filter] Script with argv '(null)' finished
[11:12:09.307] ERROR: HeWeather by Arthals[Script Filter] Code 1: .
11:12:08 workflow.py:2061 DEBUG    ---------- HeWeather by Arthals (1.3.0) ----------
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
11:12:08 connectionpool.py:959 DEBUG    Starting new HTTPS connection (1): geoapi.heweather.net:443
11:12:09 connectionpool.py:437 DEBUG    https://geoapi.heweather.net:443 "GET /v2/city/lookup?adm=changsha&location=changshaxian&key=e660101f094540c081ce20524511df8a HTTP/1.1" 200 34
11:12:09 workflow.py:2080 ERROR    'location'
Traceback (most recent call last):
  File "/Users/aeon/Google 云端硬盘/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.34D4CC5C-61E9-4E64-B3B0-49920048AF8D/workflow/workflow.py", line 2073, in run
    func(self)
  File "main.py", line 410, in main
    query_weather(wf, query_location, query_adm)
  File "main.py", line 68, in query_weather
    local_utc = geo_info['location'][0]['utcOffset']
KeyError: 'location'
11:12:09 workflow.py:2103 DEBUG    ---------- finished in 0.518s ----------
[11:12:09.310] HeWeather by Arthals[Script Filter] {"items": [{"valid": false, "subtitle": "'location'", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'HeWeather by Arthals'"}]}
[11:13:41.523] HeWeather by Arthals[Script Filter] Queuing argument ''
[11:13:42.303] HeWeather by Arthals[Script Filter] Script with argv '(null)' finished
[11:13:42.307] ERROR: HeWeather by Arthals[Script Filter] Code 1: .
11:13:41 workflow.py:2061 DEBUG    ---------- HeWeather by Arthals (1.3.0) ----------
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
11:13:41 connectionpool.py:959 DEBUG    Starting new HTTPS connection (1): geoapi.heweather.net:443
11:13:42 connectionpool.py:437 DEBUG    https://geoapi.heweather.net:443 "GET /v2/city/lookup?adm=changsha&location=changshaxian&key=e660101f094540c081ce20524511df8a HTTP/1.1" 200 34
11:13:42 workflow.py:2080 ERROR    'location'
Traceback (most recent call last):
  File "/Users/aeon/Google 云端硬盘/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.34D4CC5C-61E9-4E64-B3B0-49920048AF8D/workflow/workflow.py", line 2073, in run
    func(self)
  File "main.py", line 410, in main
    query_weather(wf, query_location, query_adm)
  File "main.py", line 68, in query_weather
    local_utc = geo_info['location'][0]['utcOffset']
KeyError: 'location'
11:13:42 workflow.py:2103 DEBUG    ---------- finished in 0.564s ----------
[11:13:42.309] HeWeather by Arthals[Script Filter] {"items": [{"valid": false, "subtitle": "'location'", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'HeWeather by Arthals'"}]}

**Comment by AeonWorks** [comment]
突然又好了……不知道什么情况。相关信息如下，供参考：

[11:37:06.391] Logging Started...
[11:37:08.854] HeWeather by Arthals[Script Filter] Queuing argument ''
[11:37:10.814] HeWeather by Arthals[Script Filter] Script with argv '(null)' finished
[11:37:10.817] STDERR: HeWeather by Arthals[Script Filter] .
11:37:09 workflow.py:2061 DEBUG    ---------- HeWeather by Arthals (1.3.0) ----------
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
11:37:09 connectionpool.py:959 DEBUG    Starting new HTTPS connection (1): geoapi.heweather.net:443
11:37:09 connectionpool.py:437 DEBUG    https://geoapi.heweather.net:443 "GET /v2/city/lookup?adm=changsha&location=changshaxian&key=e660101f094540c081ce20524511df8a HTTP/1.1" 200 276
11:37:09 connectionpool.py:959 DEBUG    Starting new HTTPS connection (1): geoapi.heweather.net:443
11:37:09 connectionpool.py:437 DEBUG    https://geoapi.heweather.net:443 "GET /v2/city/lookup?adm=changsha&location=changshaxian&key=e660101f094540c081ce20524511df8a HTTP/1.1" 200 276
11:37:09 connectionpool.py:959 DEBUG    Starting new HTTPS connection (1): devapi.heweather.net:443
11:37:09 connectionpool.py:437 DEBUG    https://devapi.heweather.net:443 "GET /v7/warning/now?location=101250106&key=e660101f094540c081ce20524511df8a HTTP/1.1" 200 152
11:37:09 connectionpool.py:959 DEBUG    Starting new HTTPS connection (1): devapi.heweather.net:443
11:37:10 connectionpool.py:437 DEBUG    https://devapi.heweather.net:443 "GET /v7/air/now?location=101250106&key=e660101f094540c081ce20524511df8a HTTP/1.1" 200 266
11:37:10 connectionpool.py:959 DEBUG    Starting new HTTPS connection (1): devapi.heweather.net:443
11:37:10 connectionpool.py:437 DEBUG    https://devapi.heweather.net:443 "GET /v7/weather/now?location=101250106&key=e660101f094540c081ce20524511df8a HTTP/1.1" 200 307
11:37:10 connectionpool.py:959 DEBUG    Starting new HTTPS connection (1): devapi.heweather.net:443
11:37:10 connectionpool.py:437 DEBUG    https://devapi.heweather.net:443 "GET /v7/weather/3d?location=101250106&key=e660101f094540c081ce20524511df8a HTTP/1.1" 200 562
11:37:10 workflow.py:1468 DEBUG    reading settings from /Users/aeon/Library/Application Support/Alfred/Workflow Data/com.arthals.weather/settings.json
11:37:10 workflow.py:2254 DEBUG    set last run version: 1.3.0
11:37:10 workflow.py:2103 DEBUG    ---------- finished in 1.736s ----------
[11:37:10.819] HeWeather by Arthals[Script Filter] {"items": [{"arg": "https://github.com/zhuozhiyongde/Alfred_HeWeather_Workflow", "valid": true, "subtitle": "  Code by Leon/Arthals\uff0cAPI by HeWeather\uff0c\u5404\u9879\u5177\u4f53\u5185\u5bb9\u53ef\u4ee5\u9009\u4e2d\u6761\u76ee\u540c\u65f6\u6309\u4f4f\u21e7\u9884\u89c8\u6216\u23ce\u6253\u5f00", "title": "\u3010\u548c\u98ce\u5929\u6c14 \u00b7 \u957f\u6c99\u53bf\u00b7 \u6e56\u5357\u7701 \u00b7 \u957f\u6c99 \u3011"}, {"subtitle": "  \u21bb 2022-01-09 11:34:00 UTC+08:00    \u63cf\u8ff0\uff1a\u6613\u611f\u4eba\u7fa4\u75c7\u72b6\u6709\u8f7b\u5ea6\u52a0\u5267\uff0c\u5065\u5eb7\u4eba\u7fa4\u51fa\u73b0\u523a\u6fc0\u75c7\u72b6", "title": "\u3010\u957f\u6c99\u53bf\u3011\u5f53\u524dAQI 127\uff0c\u8f7b\u5ea6\u6c61\u67d3", "valid": true, "arg": "http://hfx.link/1tjm4", "quicklookurl": "http://hfx.link/1tjm4", "icon": {"path": "./res/icon-aqi/3.png"}}, {"subtitle": "  \u26097\u2103\uff085\u2103\uff09    \u2601 \u4e1c\u5317\u98ce2\u7ea7    \u2602 0.0mm    \u21bb 2022-01-09 11:32:00 UTC+08:00", "title": "\u3010\u957f\u6c99\u53bf\u301111:37\uff0c\u591a\u4e91", "valid": true, "arg": "http://hfx.link/1tjm1", "quicklookurl": "http://hfx.link/1tjm1", "icon": {"path": "./res/icon-heweather/101.png"}}, {"subtitle": "   \u21934\u2103    \u21918\u2103    \u260007:21    \u263e17:49    \u26020.0mm    \u263c2(\u8f83\u4f4e,\u65e0\u9700\u9632\u6652)   \u4eca\u5929   01\u670809\u65e5   \u661f\u671f\u65e5", "title": "\u3010\u957f\u6c99\u53bf\u3011\u4eca\u5929\u767d\u5929\u591a\u4e91\uff0c\u591c\u95f4\u591a\u4e91", "valid": true, "arg": "http://hfx.link/1tjm1", "quicklookurl": "http://hfx.link/1tjm1", "icon": {"path": "./res/icon-heweather/101.png"}}, {"subtitle": "   \u21933\u2103    \u21916\u2103    \u260007:21    \u263e17:49    \u26024.2mm    \u263c1(\u8f83\u4f4e,\u65e0\u9700\u9632\u6652)   \u660e\u5929   01\u670810\u65e5   \u661f\u671f\u4e00", "title": "\u3010\u957f\u6c99\u53bf\u3011\u660e\u5929\u767d\u5929\u5c0f\u96e8\uff0c\u591c\u95f4\u591a\u4e91", "valid": true, "arg": "http://hfx.link/1tjm1", "quicklookurl": "http://hfx.link/1tjm1", "icon": {"path": "./res/icon-heweather/305.png"}}, {"subtitle": "   \u21933\u2103    \u219110\u2103    \u260007:21    \u263e17:50    \u26020.0mm    \u263c4(\u4e2d\u7b49,\u9002\u5f53\u9632\u6652)   \u540e\u5929   01\u670811\u65e5   \u661f\u671f\u4e8c", "title": "\u3010\u957f\u6c99\u53bf\u3011\u540e\u5929\u767d\u5929\u6674\uff0c\u591c\u95f4\u6674", "valid": true, "arg": "http://hfx.link/1tjm1", "quicklookurl": "http://hfx.link/1tjm1", "icon": {"path": "./res/icon-heweather/100.png"}}]}

**Comment by zhuozhiyongde** [comment]
似乎是你环境变量少填了，目前是需要在预设填一次，然后如果查询非预设的需要打 `rt location` 这样的。

**Comment by AeonWorks** [comment]
> 似乎是你环境变量少填了，目前是需要在预设填一次，然后如果查询非预设的需要打 `rt location` 这样的。

感谢回复。我重新配置了环境变量就好了。之前出问题的时候，其实也有好几次是好的，我没有动过环境变量，开始就配置了的。

**Comment by zhuozhiyongde** [comment]
哈哈 能用了就行=w=
