### ISSUE TITLE
macOS更新到12.3，安装最新的python3，用不了了

### ISSUE THREAD

**Issue by AeonWorks** [zhuozhiyongde/Alfred_HeWeather_Workflow#3]
错误信息如下：

[15:14:19.616] HeWeather by Arthals[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.34D4CC5C-61E9-4E64-B3B0-49920048AF8D%3E50B0CD10-4D52-4898-9C05-DD3A34A829C3)] Queuing argument ''
[15:14:19.718] HeWeather by Arthals[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.34D4CC5C-61E9-4E64-B3B0-49920048AF8D%3E50B0CD10-4D52-4898-9C05-DD3A34A829C3)] Script with argv '(null)' finished
[15:14:19.719] ERROR: HeWeather by Arthals[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.34D4CC5C-61E9-4E64-B3B0-49920048AF8D%3E50B0CD10-4D52-4898-9C05-DD3A34A829C3)] Code 1: Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from workflow import Workflow3
  File "/Users/aeon/Google Drive/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.34D4CC5C-61E9-4E64-B3B0-49920048AF8D/workflow/__init__.py", line 16, in <module>
    from .workflow import Workflow, manager
  File "/Users/aeon/Google Drive/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.34D4CC5C-61E9-4E64-B3B0-49920048AF8D/workflow/workflow.py", line 25, in <module>
    import cPickle
ModuleNotFoundError: No module named 'cPickle'

**Comment by zhuozhiyongde** [comment]
本项目所用的框架是基于python2.7搭建的，请等待框架作者更新。

**Comment by zhuozhiyongde** [comment]
您可以参考：https://github.com/deanishe/alfred-workflow/issues/182

**Comment by zhuozhiyongde** [comment]
我最近换电脑，更新到了MacOS 12，发现很多原先的Alfred python项目都无法使用
但我很快解决了：只需要在[官网](https://python.org)重新安装Python2即可
供参考。
